export const CARD_CUSTUMER = [
	{
		icons: 'tower',
		title: 'Transmission System Operators (TSOs)',
		subtitle: 'Enhance grid management with Enline’s cutting-edge solutions.',
		urlCustomer: '/customer/tso',
		iconFirstButton: require('@/assets/svg/icon_liveview.svg'),
		altFirstButton: 'icon_liveview',
		textFirstButton: 'Enline LiveView',
		urlFirstButton: '/solutions/liveview',
		iconSecondButton: require('@/assets/svg/icon_predictpro.svg'),
		altSecondButton: 'icon_predictpro',
		textSecondButton: 'Enline PredictPro',
		urlSecondButton: '/solutions/predictpro'
	},
	{
		icons: 'distribution',
		title: 'Distribution System Operators (DSOs)',
		subtitle: 'Streamline operations and optimize performance with Enline.',
		urlCustomer: '/customer/dso',
		iconFirstButton: require('@/assets/svg/icon_liveview.svg'),
		altFirstButton: 'icon_liveview',
		textFirstButton: 'Enline LiveView',
		urlFirstButton: '/solutions/liveview',
		iconSecondButton: require('@/assets/svg/icon_optimax.svg'),
		altSecondButton: 'icon_optimax',
		textSecondButton: 'Enline OptiMax',
		urlSecondButton: '/solutions/optimax'
	},
	{
		icons: 'electrical_box',
		title: 'Power Generation Companies',
		subtitle: 'Harness the power of data-driven insights to maximize efficiency.',
		urlCustomer: '/customer/power_generation',
		iconFirstButton: require('@/assets/svg/icon_liveview.svg'),
		altFirstButton: 'icon_liveview',
		textFirstButton: 'Enline LiveView',
		urlFirstButton: '/solutions/liveview',
		iconSecondButton: require('@/assets/svg/icon_smartdesign.svg'),
		altSecondButton: 'icon_smartdesign',
		textSecondButton: 'Enline SmartDesign',
		urlSecondButton: '/solutions/smartdesign'
	},
	{
		icons: 'risk_management',
		title: 'Risk Management and Insurance Companies',
		subtitle: 'Assess and mitigate risks with Enline’s state-of-the-art solutions.',
		urlCustomer: '/customer/risk_management',
		iconFirstButton: require('@/assets/svg/icon_liveview.svg'),
		altFirstButton: 'icon_liveview',
		textFirstButton: 'Enline LiveView',
		urlFirstButton: '/solutions/liveview',
		iconSecondButton: require('@/assets/svg/icon_predictpro.svg'),
		altSecondButton: 'icon_predictpro',
		textSecondButton: 'Enline PredictPro',
		urlSecondButton: '/solutions/predictpro'
	},
	{
		icons: 'renewable',
		title: 'Renewable Energy Providers',
		subtitle: 'Accelerate the transition to clean energy with Enline’s solutions.',
		urlCustomer: '/customer/renewable_energy',
		iconFirstButton: require('@/assets/svg/icon_liveview.svg'),
		altFirstButton: 'icon_liveview',
		textFirstButton: 'Enline LiveView',
		urlFirstButton: '/solutions/liveview',
		iconSecondButton: require('@/assets/svg/icon_predictpro.svg'),
		altSecondButton: 'icon_predictpro',
		textSecondButton: 'Enline PredictPro',
		urlSecondButton: '/solutions/predictpro'
	},
	{
		icons: 'research',
		title: 'Research & Development institutions',
		subtitle: 'Harness the power of data for groundbreaking discoveries.',
		urlCustomer: '/customer/energy_research',
		iconFirstButton: require('@/assets/svg/icon_optimax.svg'),
		altFirstButton: 'icon_optimax',
		textFirstButton: 'Enline OptiMax',
		urlFirstButton: '/solutions/optimax',
		iconSecondButton: require('@/assets/svg/icon_smartdesign.svg'),
		altSecondButton: 'icon_smartdesign',
		textSecondButton: 'Enline SmartDesign',
		urlSecondButton: '/solutions/smartdesign'
	},
	{
		icons: 'electric',
		title: 'Electric Vehicle (EV) Infrastructure Providers',
		subtitle: 'Boost the reliability and efficiency of your EV infrastructure with Enline.',
		urlCustomer: '/customer/electric_mobility',
		iconFirstButton: require('@/assets/svg/icon_liveview.svg'),
		altFirstButton: 'icon_liveview',
		textFirstButton: 'Enline LiveView',
		urlFirstButton: '/solutions/liveview',
		iconSecondButton: require('@/assets/svg/icon_optimax.svg'),
		altSecondButton: 'icon_optimax',
		textSecondButton: 'Enline OptiMax',
		urlSecondButton: '/solutions/optimax'
	},
	{
		icons: 'industry',
		title: 'Industry and Mining Companies',
		subtitle: 'Achieve maximum efficiency in your energy infrastructure.',
		urlCustomer: '/customer/industry',
		iconFirstButton: require('@/assets/svg/icon_optimax.svg'),
		altFirstButton: 'icon_optimax',
		textFirstButton: 'Enline OptiMax',
		urlFirstButton: '/solutions/optimax',
		iconSecondButton: require('@/assets/svg/icon_safeguard.svg'),
		altSecondButton: 'icon_safeguard',
		textSecondButton: 'Enline SafeGuard',
		urlSecondButton: '/solutions/safeguard'
	},
	{
		icons: 'operation',
		title: 'Operations & Maintenance (O&M)',
		subtitle: 'Drive efficiency and extend asset life through data-driven strategies.',
		urlCustomer: '/customer/operations',
		iconFirstButton: require('@/assets/svg/icon_liveview.svg'),
		altFirstButton: 'icon_liveview',
		textFirstButton: 'Enline LiveView',
		urlFirstButton: '/solutions/liveview',
		iconSecondButton: require('@/assets/svg/icon_predictpro.svg'),
		altSecondButton: 'icon_predictpro',
		textSecondButton: 'Enline PredictPro',
		urlSecondButton: '/solutions/predictpro'
	}
];
